add login validator
CodersCamp2021/team-lp-project-5 pull request #10
Opened 2022-05-11 21:18 UTC by patrykbrodziak1

2022-05-12 07:30 UTC, Burbinox approved these changes
LGTM

2022-05-12 11:47 UTC, kubaczerwinski77 requested changes
I left some comments about validation rules. Check them out.

2022-05-12 11:47 UTC, kubaczerwinski77 commented on common/validators.js
> +    username: yup.string().required(),
I would suggest signing in using email rather than username.

2022-05-12 11:47 UTC, kubaczerwinski77 commented on common/validators.js
> +    password: yup.string().required(),
We need more validation rules about password. Think about min / max characters, numbers or special characters.

2022-05-12 12:32 UTC, patrykbrodziak1 commented on common/validators.js
> +    username: yup.string().required(),
ok, email and password, yes?

2022-05-12 13:46 UTC, kubaczerwinski77 commented on common/validators.js
> +    username: yup.string().required(),
Yup

2022-05-15 10:14 UTC, kubaczerwinski77 approved these changes

2022-05-15 11:40 UTC, merged