New/create task
CodersCamp2021/team-lp-project-5 pull request #3
Opened 2022-05-10 16:24 UTC by Burbinox

2022-05-10 20:45 UTC, patrykbrodziak1 approved these changes

2022-05-11 20:23 UTC, pastepi commented on server/routes/task.js
> +    const response = await TaskControler.createTask(req.body);
```suggestion
    const response = await TaskController.createTask(req.body);
```

2022-05-11 20:23 UTC, pastepi commented on server/routes/task.js
> +import TaskControler from "../controllers/task.js";
```suggestion
import TaskController from "../controllers/task.js";
```

2022-05-11 22:59 UTC, pastepi requested changes
Look at the suggestions above.
Also, in files that use `process.env...` please put in this `import "dotenv/config";`
Other than that, this works (I assume we don't want any validation at this point?).

2022-05-12 10:27 UTC, Burbinox commented
> Look at the suggestions above. Also, in files that use `process.env...` please put in this `import "dotenv/config";` Other than that, this works (I assume we don't want any validation at this point?).

2022-05-12 11:13 UTC, pastepi commented
> > Look at the suggestions above. Also, in files that use `process.env...` please put in this `import "dotenv/config";` Other than that, this works (I assume we don't want any validation at this point?).
> 
> Why should I? I have PORT in my system variables so I don't need to import "dotenv/config". Same with the DATABASE_PASSWORD.
Resolved in DMs, ended up adding the import.

2022-05-12 11:14 UTC, pastepi approved these changes

2022-05-12 11:20 UTC, merged