add date to create task
CodersCamp2021/team-lp-project-5 pull request #32
Opened 2022-05-19 07:13 UTC by patrykbrodziak1

2022-05-19 09:09 UTC, kubaczerwinski77 requested changes
The only suggestion is to change function name, because now we update all task properties - not only priority or status.

2022-05-19 23:21 UTC, pastepi requested changes

2022-05-19 23:21 UTC, pastepi commented on server/controllers/task.js
> +      `INSERT INTO tasks (title, description, user_id, priority, status, due_date) VALUES ($1, $2, $3, $4, $5, $7);`,
Any reason for `$7` and not `$6` here?

2022-05-20 06:59 UTC, patrykbrodziak1 commented on server/controllers/task.js
> +      `INSERT INTO tasks (title, description, user_id, priority, status, due_date) VALUES ($1, $2, $3, $4, $5, $7);`,
no, missclick ofc

2022-05-21 15:55 UTC, pastepi approved these changes

2022-05-21 15:55 UTC, pastepi commented on server/controllers/task.js
> +  static changeTaskInfo = async (req) => {
We need to change the method name and endpoint url in the tasks router as well.

2022-05-21 17:11 UTC, patrykbrodziak1 commented on server/controllers/task.js
> +  static changeTaskInfo = async (req) => {
I think it's okay. what endpoint name do you suggest?

2022-05-21 17:11 UTC, patrykbrodziak1 commented on server/controllers/task.js
> +  static changeTaskInfo = async (req) => {
![image](https://user-images.githubusercontent.com/95182056/169662105-fcbc9c06-4304-4dbf-b9b1-5ac95884e819.png)

2022-05-21 17:29 UTC, pastepi approved these changes

2022-05-22 10:15 UTC, kubaczerwinski77 approved these changes

2022-05-22 11:12 UTC, merged