New/calendar
CodersCamp2021/team-lp-project-5 pull request #8
Opened 2022-05-11 17:59 UTC by macjank

- add calendar page
- add routing
- add calendar component
- add tasks component

2022-05-12 14:15 UTC, kubaczerwinski77 submitted a review, later dismissed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86623851/168095604-d2455a81-e53e-4c80-9817-df9ba625e858.png">
Unfortunately the scroll appeared :((

2022-05-12 14:45 UTC, pastepi requested changes
Some small changes to be made, other than that it looks 👍

2022-05-12 14:45 UTC, pastepi commented on client/src/utils/checkIfTheSameDay.js
> +export const checkIfTheSameDay = (firstDate, secondDate) => {
could simplify it a bit to just return `firstDate.toDateString() === secondDate.toDateString()`

2022-05-12 14:45 UTC, pastepi commented on client/src/utils/taskPriorities.js
> +export const taskPriorities = Object.freeze({
Instead of creating a separate file, move this to `other` inside `theme` object.

2022-05-12 14:45 UTC, pastepi commented on client/src/components/calendar/SingleTask.jsx
> +        {title}
Right now the title can overflow and break the task tile, we either need to handle this with styling or make sure we set proper character limits for `title` field.

2022-05-12 16:06 UTC, pastepi commented on client/src/components/calendar/SingleTask.jsx
> +      style={{
I'd move the css from `style` into something like `use-task-styles.js` as you did with `use-calendar-page-styles.js`

2022-05-12 16:07 UTC, pastepi commented on client/src/components/calendar/Tasks.jsx
> +        style={{
I'd move these into `use-calendar-page-styles`

2022-05-15 16:48 UTC, pastepi requested changes

2022-05-15 16:48 UTC, pastepi commented on client/src/App.js
> +        <Route path="/calendar" element={<CalendarPage />} />
Don't need this, we already have `/calendar` route in `Shell.jsx`

2022-05-15 16:48 UTC, pastepi commented on client/src/App.js
>          <Route path="/" element={<Shell />} />
```suggestion
        <Route path="/*" element={<Shell />} />
```
While we're here add this, we missed it earlier.

2022-05-15 18:22 UTC, pastepi approved these changes

2022-05-15 18:22 UTC, pastepi approved these changes

2022-05-15 18:22 UTC, pastepi approved these changes

2022-05-15 18:25 UTC, merged